ecommerce/Cart/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('', views.cart ,name='cart-page'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add-product'),
    path('delete_cartitem/<int:product_id>/<int:cart_item_id>/', views.delete_cartitem, name='delete_cartitem'),
    path('remove_cartitem/<int:product_id>/<int:cart_item_id>/', views.remove_cartitem, name='remove_cartitem'),
    path('checkout/', views.checkout , name='checkout' ),
    path('wishlist/',views.view_wishlist, name='wishlist'),
    path('addwishlist', views.add_wishlist , name='addwishlist'),
    path("apply_coupon", views.Check_coupon, name="apply_coupon"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
     
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('user/', include('Users.urls')),
    path('store/', include('store.urls')),
    path('cart/',include('Cart.urls')),
    path('adminapp/',include('Admin_app.urls')),
    path('orders/', include('Orders.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerce/store/urls.py
from django.urls import path
from .import views
urlpatterns = [
    path('', views.store,name='store-page'),
    path('category/<slug:category_slug>/',views.store , name='products_by_category'),
    path('category<slug:category_slug>/<slug:product_slug>/',views.product_detail , name='product_detail'),
    path('search/', views.search ,name='search-product'),
]

ecommerce/store/models.py
from email.policy import default
from enum import unique
from random import choices
from django.db import models
from catagory.models import Catogory
from django.urls import reverse
from Offer.models import Offers

# Create your models here.

class Product(models.Model):
    product_name  =  models.CharField(max_length=200, unique=True)
    slug          =  models.SlugField(max_length=200, unique=True)
    description   =  models.CharField(max_length=500,blank=True)
    price         =  models.IntegerField()
    stock         =  models.IntegerField()
    is_available  =  models.BooleanField(default=True)
    product_img   =  models.ImageField(upload_to= 'product_img')
    catogory      =  models.ForeignKey(Catogory , on_delete=models.CASCADE)
    created_field =  models.DateTimeField(auto_now_add=True)
    modified_field=  models.DateTimeField(auto_now=True)
    offer         =  models.ForeignKey(Offers, blank=True,null=True,on_delete=models.SET_NULL)
    actual_price  =  models.IntegerField(null=True , blank=True)

    def __str__(self):
        return self.product_name

    def get_url(self):
        return reverse('product_detail', args=[self.catogory.slug,self.slug])

    




class VariationManager(models.Manager):
    # def colors(self):
    #     return super(VariationManager,self).filter(variation_catogory='color', is_active=True)

    def size(self):
        return super(VariationManager,self).filter(variation_catogory='size', is_active=True)


variation_category_choice=( 
                             ('size','size'),)

            

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_catogory = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active= models.BooleanField(default=True)
    created_date = models.DateField(auto_now=True)

    objects =VariationManager()

    def __str__(self):
        return self.variation_value



class ProductGallery(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='store/products', max_length=255)

    def __str__(self):
        return self.product.product_name

    class Meta:
        verbose_name = 'productgallery'
        verbose_name_plural = 'product gallery'

ecommerce/store/views.py
from ast import keyword
from itertools import product

from django.http import HttpResponse
from django.shortcuts import redirect, render , get_object_or_404
from .models import Product,ProductGallery
from catagory.models import Catogory
from Cart.models import Cartitem,Cart
from Cart.views import get_cartid
from django.db.models import Q

# Create your views here.

def store(request,category_slug=None):
    categories = None
    product  = None
    if category_slug != None:
        categories = get_object_or_404(Catogory , slug = category_slug)
        product    = Product.objects.filter(catogory= categories , is_available= True)
        product_count = product.count()

    else:
        product = Product.objects.all().filter(is_available=True)
        product_count= product.count()
    content ={
        "products":product,
        "products_count":product_count
        }
    return render(request , 'store/store.html', content)

def product_detail(request,category_slug,product_slug):

    try:
        single_product=Product.objects.get(catogory__slug=category_slug, slug=product_slug)
        iscart_id= Cartitem.objects.filter(product=single_product,cart__cart_id=get_cartid(request)).exists()
        
        

    except Exception as e:
        raise e

    # product gallery
    product_gallery = ProductGallery.objects.filter(product_id=single_product.id)

    context = {"single_product":single_product,
               "iscart_id" : iscart_id,
               "product_gallery":product_gallery    }

    return render(request, 'store/product_detail.html', context)


def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.filter(Q(product_name__icontains=keyword)| Q(description__icontains= keyword))
            product_count= products.count()

            context={ 
                'products':products,
                "products_count":product_count
                }

    return render(request, 'store/store.html',context)

ecommerce/store/templates/store/product_detail.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container">

    <!-- ============================ COMPONENT 1 ================================= -->
    <div class="card">
      <div class="row no-gutters ">
        <aside class="col-md-6">
          <article class="gallery-wrap ">
            <!-- <div class="img-big-wrap mainImage  cart__item"> -->
              <div id="img-container">
                <div id="lens"></div>
                <img id="featured" src="{{ single_product.product_img.url }}" class='img-fluid'>
            </div>
                    <div id="slide-wrapper">
                        <img id="slideLeft" class="arrow" src="{{ single_product.product_img.url }}">

                        <div id="slider">
                          {% for i in product_gallery %}
                            <img class="thumbnail " src="{{ i.image.url }}">
                            {% endfor %}
                        </div>

                        <img id="slideRight" class="arrow" src="{{ single_product.product_img.url }}">
                    </div>
                <!-- <center><img src="{{single_product.product_img.url}}"></center> -->
              <!-- <div class="zoom">
                <img src="{{single_product.product_img.url}}">
              </div> -->
             <!-- img-big-wrap.// -->
          </article><!-- gallery-wrap .end// -->
          <!-- product gallery -->
          <!-- <ul class="thumb">
            <li>
              <a href="{{ single_product.product_img.url }}" target="mainImage"><img
                  src="{{ single_product.product_img.url }}" alt="Product Image"></a>
              {% for i in product_gallery %}
              <a href="{{i.image.url}}" target="mainImage"><img src="{{i.image.url}}" alt="Product Image"></a>
              {% endfor %}
            </li>
          </ul> -->
        </aside>
        <main class="col-md-6 border-left">
          <form action="{% url 'add-product' single_product.id %}" method="POST">
            {% csrf_token %}



            <article class="content-body">

              <h2 class="title">{{single_product.product_name}}</h2>

              <div class="mb-3">
                <var class="price h4">Rs {{single_product.price}}</var>
              </div>

              <p>{{single_product.description}}.</p>


              <hr>

              <div class="row">
                <div class="item-option-select">
                  <h6>Select Size</h6>
                  <div class="btn-group btn-group-sm btn-group-toggle" data-toggle="buttons">
                    {% for i in single_product.variation_set.size %}
                    <label class="btn btn-light">
                      <input type="radio" name="size" value="{{i.variation_value}}"> {{i.variation_value}}

                    </label>
                    {% endfor %}
                    <!-- <label class="btn btn-light active">
                    <input type="radio" name="size" value="medium" checked> M
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="size" value="large"> L
                  </label>
                  <label class="btn btn-light">
                    <input type="radio" name="size" value="extralarge"> XL
                  </label> -->
                  </div>
                </div>
              </div> <!-- row.// -->
              <hr>
              {% if single_product.stock > 0 %}

              <button type="submit" class="btn  btn-primary"> <span class="text">Add to cart</span> <i
                  class="fas fa-shopping-cart"></i> </button>

              {% else %}
              <h1 class="text-danger"> OUT OF STOCK </h1>
              {% endif %}
            </article>
          </form>
          <!-- product-info-aside .// -->
        </main> <!-- col.// -->

      </div> <!-- row.// -->
    </div> <!-- card.// -->
    <!-- ============================ COMPONENT 1 END .// ================================= -->

    <br>

    <div class="row">
      <div class="col-md-9">

        <header class="section-heading">
          <h3>Customer Reviews </h3>

        </header>

        <article class="box mb-3">
          <div class="icontext w-100">
            <img src="./images/avatars/avatar1.jpg" class="img-xs icon rounded-circle">
            <div class="text">
              <span class="date text-muted float-md-right">24.04.2020 </span>
              <h6 class="mb-1">Mike John </h6>

            </div>
          </div> <!-- icontext.// -->
          <div class="mt-3">
            <p>
              Dummy comment Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
              quis nostrud exercitation ullamco laboris nisi ut aliquip
            </p>
          </div>
        </article>



      </div> <!-- col.// -->
    </div> <!-- row.// -->


  </div> <!-- container .//  -->
</section>
<script>
  document.getElementById('img-container').addEventListener('mouseover', function(){
    imageZoom('featured')
    
})

function imageZoom(imgID){
	let img = document.getElementById(imgID)
	let lens = document.getElementById('lens')

	lens.style.backgroundImage = `url( ${img.src} )`

	let ratio = 3

	lens.style.backgroundSize = (img.width * ratio) + 'px ' + (img.height * ratio) + 'px';

	img.addEventListener("mousemove", moveLens)
	lens.addEventListener("mousemove", moveLens)
	img.addEventListener("touchmove", moveLens)

	function moveLens(){
		/*
        Function sets sets position of lens over image and background image of lens
        1 - Get cursor position
        2 - Set top and left position using cursor position - lens width & height / 2
        3 - Set lens top/left positions based on cursor results
        4 - Set lens background position & invert
        5 - Set lens bounds
    
        */

        //1
		let pos = getCursor()
		//console.log('pos:', pos)

		//2
		let positionLeft = pos.x - (lens.offsetWidth / 2)
		let positionTop = pos.y - (lens.offsetHeight / 2)

		//5
		if(positionLeft < 0 ){
			positionLeft = 0
		}

		if(positionTop < 0 ){
			positionTop = 0
		}

		if(positionLeft > img.width - lens.offsetWidth /3 ){
			positionLeft = img.width - lens.offsetWidth /3
		}

		if(positionTop > img.height - lens.offsetHeight /3 ){
			positionTop = img.height - lens.offsetHeight /3
		}


		//3
		lens.style.left = positionLeft + 'px';
		lens.style.top = positionTop + 'px';

		//4
		lens.style.backgroundPosition = "-" + (pos.x * ratio) + 'px -' +  (pos.y * ratio) + 'px'
	}

	function getCursor(){
		/* Function gets position of mouse in dom and bounds
         of image to know where mouse is over image when moved
        
        1 - set "e" to window events
        2 - Get bounds of image
        3 - set x to position of mouse on image using pageX/pageY - bounds.left/bounds.top
        4- Return x and y coordinates for mouse position on image
        
         */

        let e = window.event
        let bounds = img.getBoundingClientRect()

        //console.log('e:', e)
        //console.log('bounds:', bounds)
        let x = e.pageX - bounds.left
		let y = e.pageY - bounds.top
		x = x - window.pageXOffset;
		y = y - window.pageYOffset;
		
		return {'x':x, 'y':y}
	}

}

imageZoom('featured')
</script> 
<script>
  let thumbnails = document.getElementsByClassName('thumbnail')

let activeImages = document.getElementsByClassName('active')

for (var i=0; i < thumbnails.length; i++){

	thumbnails[i].addEventListener('click', function(){
		console.log(activeImages)
		
		if (activeImages.length > 0){
			activeImages[0].classList.remove('active')
		}
		

		this.classList.add('active')
		document.getElementById('featured').src = this.src
	})
}


let buttonRight = document.getElementById('slideRight');
let buttonLeft = document.getElementById('slideLeft');

buttonLeft.addEventListener('click', function(){
	document.getElementById('slider').scrollLeft -= 180
})

buttonRight.addEventListener('click', function(){
	document.getElementById('slider').scrollLeft += 180
})
</script>

<style>
#featured {
cursor: pointer;
}

.thumbnail {
object-fit: cover;
max-width: 180px;
max-height: 100px;
cursor: pointer;
opacity: 0.5;
margin: 5px;
border: 2px solid black;

}

.thumbnail:hover {
opacity: 1;
}

.active {
opacity: 1;
}

#slide-wrapper {
margin-top: 30px;
max-width: 500px;
display: flex;
min-height: 100px;
align-items: center;
}

#slider {
width: 440px;
display: flex;
flex-wrap: nowrap;
overflow-x: auto;

}

#slider::-webkit-scrollbar {
width: 8px;

}

/* #slider::-webkit-scrollbar-track {
-webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);

} */

#slider::-webkit-scrollbar-thumb {
background-color: #dede2e;
outline: 1px solid slategrey;
border-radius: 100px;

}

#slider::-webkit-scrollbar-thumb:hover {
background-color: #18b5ce;
}

.arrow {
width: 30px;
height: 30px;
cursor: pointer;
transition: .3s;
}

.arrow:hover {
opacity: .5;
width: 35px;
height: 35px;
}

#img-container {
z-index: 1;
max-width: 500px;
position: relative;
}

#lens {
z-index: 2;
position: absolute;

height: 125px;
width: 125px;

background-repeat: no-repeat;
cursor: none;

}

</style>

{% endblock content %}

ecommerce/store/templates/store/store.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container-fluid">
        {% if 'search' in request.path %}
        <h2 class="title-page">Search Result</h2>
        {% else %}
        <h2 class="title-page">Our Store</h2>
        {% endif %}
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container-fluid">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Categories</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" >
                <div class="card-body">
                    
                    <ul class="list-menu">
                    <li><a href="{% url 'store-page' %}">All products</a></li>
                    {% for category in link %}
                    <li><a href="{{category.get_url}}">{{category.catagory_name}}</a></li>
                    {% endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_4" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Sizes </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_4" >
                <div class="card-body">
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XS </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> SM </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> LG </span>
                  </label>
    
                  <label class="checkbox-btn">
                    <input type="checkbox">
                    <span class="btn btn-light"> XXL </span>
                  </label>
            </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range </h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" >
                <div class="card-body">
                    
                    <div class="form-row">
                    <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                    </div> <!-- form-row.// -->
                    <button class="btn btn-block btn-primary">Apply</button>
                </div><!-- card-body.// -->
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto"><b>{{products_count}} </b> Items found </span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">

        {% for product in products %}
        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap  mw-100"> 
                    
                    <a href="{{product.get_url}}" class="img-wrap">  <img src="{{product.product_img.url}}"></a>
                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{product.get_url}}" class="title">{{product.product_name}}</a>
                        <div class="price-wrap mt-2">
                            {% if product.offer %}
							<b style="color: red;">{{product.offer.discout}}% off</b><br>
							<span class="price"><del>Rs{{product.actual_price}}</del>   RS {{product.price}}</span>
							{%else%}
                            <span class="price">Rs {{product.price}}</span>
                            {% endif %}
                        </div> <!-- price-wrap.// -->
                    </div>
                    {% if product.stock <= 0 %}
                     <h4 class="text-danger">out of stocks </h4>
                     {% else %}
                     
                     <button  value={{product.id}}  class="wishlist_btn btn btn-block btn-outline-success wishlist-item" >Wishlist ❤️</button>
                     <!-- <a  onclick="add_wishlist()" id="asdfghj" value={{product.id}} class="wishlist_btn btn btn-block btn-outline-success ">Wishlist ❤️</a> -->
                    <a href="{{product.get_url}}" class="btn btn-block btn-primary"  >View Product </a>
                    {% endif %}
                </figcaption>
            </figure>
        </div> <!-- col.// -->

     {% endfor %}
    
    </div>    
    
    <nav class="mt-4" aria-label="Page navigation sample">
      <ul class="pagination">
        <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item active"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
      </ul>
    </nav>
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
    
  
<script>
    [...document.getElementsByClassName('wishlist-item')].forEach(function (e){
        e.addEventListener('click', function(){
            id = Number(this.getAttribute('value'))
            
            
            console.log(id)
            $.ajax({
                
                url:'/cart/addwishlist',
                method:'GET',
                dataType: 'json',
                data: {
                    id:id
                },
                success:(response) => {
                    if (response.flag == 1){
                        swal("Sorry!", "Already wishlisted", "error");
                    }
                    else if(response.flag == 2){
                        swal("Successful!", "Wishlisted", "success");
                    }
                }
            })
        })
    })
</script>    
{% endblock content %}